### ISSUE TITLE
Ticket required

### ISSUE THREAD

**Issue by undeaDD** [Jake0oo0/r6api#1]
When i try to open the api urls with my modified header it displays the following:

{"errorCode":3,"errorContext":"Ubisoft.Identity.Services","httpCode":401,"message":"Ticket is required","moreInfo":"","transactionId":"f3c058d8-3ffc-4d5a-83ea-e8f54d9e3489","transactionTime":"2016-07-31T15:35:10.2548544Z"}

They now want a Ticket and not only id and token.
Do you anything about that ?!

**Comment by jengel3** [comment]
Will look into it soon. I don't really use this project anymore since we now use a private project for R6Stats

**Comment by undeaDD** [comment]
:O didnt know that website ^^
you can close this issue.

ill be using the r6stats webste instead ;)

(ps: im using it to display our team statistics on our website ...)
thx

**Comment by jengel3** [comment]
Haha okay. Shoot me an email and I'll let you in on some secret info
regarding using R6Stats for personal projects.

**Comment by undeaDD** [comment]
Hey

I sent you an Email (jake0oo0dev@gmail.com)
I already did implement my Stats extraction: **http://www.totalegal.xyz/**
(Its work in progress though so dont judge me :P )

But its slow and could be way faster and smaller with an alternative way (api, json, etc)
Im currently scraping the r6stats website with php to save the data in my private msql db.

**Comment by jengel3** [comment]
Will get back to you ASAP, super busy right now.
